name: Node.js CI

on:
  push:
    branches: 
      - master
      - payment-abstractions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
#    - name: Install Dependecies
#      run: |
#        chmod +x .github/workflows/script/install.sh
#        .github/workflows/script/install.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm -g install js-beautify
    - name: Beautify
      run: |
        chmod +x .github/workflows/scripts/install.sh
        .github/workflows/scripts/install.sh
#    - run: npm run build --if-present
#    - run: npm test
      env:
        CI: true
